#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

compton --config /home/shaddai/.config/picom/picom.conf &
#wmname LG3D &
feh --bg-fill /home/shaddai/Backgrounds/image27.jpg &
~/.config/polybar/launch_polybar.sh &
#/usr/bin/polybar &
xfce4-power-manager &
#/usr/bin/polybar &
killall mate-notification-daemon; dunst &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a  desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Yaak state=tiled

bspc config focus_follows_pointer true
picom experimental-backends &
bsp config border_width 0
# setxkbmap latam &
setxkbmap -layout us -variant intl &
xsettings
vmware-user-suid-wrapper &
xrandr --output eDP-1 --brightness 0.5 &
xrandr -s 1920x1080 &
