# absolute-black theme
window_padding_width 10

# Special
foreground #e2e2e2
background #080808

# Black
color0  #1c1c1c
color8  #505050

# Red
color1  #ff4455
color9  #ff6677

# Green
color2  #00d4aa
color10 #20f0c0

# Yellow
color3  #00d4ff
color11 #40e8ff

# Blue
color4  #5588cc
color12 #00d4ff

# Magenta
color5  #8866cc
color13 #aa88ee

# Cyan
color6  #00aad4
color14 #00d4ff

# White
color7  #b0b0b0
color15 #e2e2e2

# Cursor
cursor              #00d4ff
cursor_text_color   #080808

# Selection
selection_foreground #e2e2e2
selection_background #1c1c1c

# Tab bar
active_tab_foreground   #080808
active_tab_background   #00d4ff
active_tab_font_style   bold
inactive_tab_foreground #505050
inactive_tab_background #101010
inactive_tab_font_style normal
tab_bar_background      #080808
tab_bar_margin_width    0.0
tab_bar_margin_height   6.0 2.0
