# rose-pine theme
window_padding_width 10

# Special
foreground #e0def4
background #191724

# Black
color0  #26233a
color8  #6e6a86

# Red
color1  #eb6f92
color9  #eb6f92

# Green
color2  #31748f
color10 #9ccfd8

# Yellow
color3  #f6c177
color11 #f6c177

# Blue
color4  #9ccfd8
color12 #9ccfd8

# Magenta
color5  #c4a7e7
color13 #c4a7e7

# Cyan
color6  #ebbcba
color14 #9ccfd8

# White
color7  #e0def4
color15 #e0def4

# Cursor
cursor              #ebbcba
cursor_text_color   #191724

# Selection
selection_foreground #e0def4
selection_background #26233a

# Tab bar
active_tab_foreground   #191724
active_tab_background   #c4a7e7
active_tab_font_style   bold
inactive_tab_foreground #908caa
inactive_tab_background #1f1d2e
inactive_tab_font_style normal
tab_bar_background      #191724
tab_bar_margin_width    0.0
tab_bar_margin_height   6.0 2.0
