# dracula theme
window_padding_width 10

# Special
foreground #f8f8f2
background #1e1f29

# Black
color0  #21222c
color8  #6272a4

# Red
color1  #ff5555
color9  #ff6e6e

# Green
color2  #50fa7b
color10 #69ff94

# Yellow
color3  #f1fa8c
color11 #ffffa5

# Blue
color4  #bd93f9
color12 #d6acff

# Magenta
color5  #ff79c6
color13 #ff92df

# Cyan
color6  #8be9fd
color14 #a4ffff

# White
color7  #f8f8f2
color15 #ffffff

# Cursor
cursor              #f8f8f2
cursor_text_color   #282a36

# Selection
selection_foreground #f8f8f2
selection_background #44475a

# Tab bar
active_tab_foreground   #282a36
active_tab_background   #bd93f9
active_tab_font_style   bold
inactive_tab_foreground #6272a4
inactive_tab_background #282a36
inactive_tab_font_style normal
tab_bar_background      #1e1f29
tab_bar_margin_width    0.0
tab_bar_margin_height   6.0 2.0
